/**
 * This package contained some example bytecode generated by {@link org.objectweb.asm.util.ASMifier}.
 * It was used during the development phase. The only class left is the {@link com.github.drstefanfriedrich.f2blib.example.Dumper}.
 */
package com.github.drstefanfriedrich.f2blib.example;
